//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class EmployeeMaster
    {
        public int Id { get; set; }

        [Required]
        [StringLength(50)]

        public string Name { get; set; }

        [Required]
        [StringLength(50)]
        public string Surname { get; set; }

        [Required]
        [StringLength(500)]
        public string Address { get; set; }

        [Required]
        [StringLength(50)]
        public string Qualification { get; set; }

        [Required]
        [Display(Name = "Contact Number")]
        [StringLength(12)]
        public string Contact_Number { get; set; }

        [Required]
        [Display(Name = "Department")]
        public Nullable<int> DepartmentId { get; set; }

        public IEnumerable<SelectListItem> Departments { get; set; }

        public string DepartmentName { get; set; }
    }
}
